---
- name: Configure firefox
  block:
    - name: Ensure config folder exists
      ansible.builtin.file:
        path: "{{ firefox_config_dir }}"
        state: directory
        mode: "0750"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Create profiles config
      ansible.builtin.template:
        src: "profiles.ini.j2"
        dest: "{{ firefox_profile_config_path }}"
        mode: "0664"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Create profile folder
      ansible.builtin.file:
        path: "{{ firefox_config_dir }}/{{ firefox_profile_dir }}"
        state: directory
        mode: "0700"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Create user preferences
      ansible.builtin.template:
        src: "user.js.j2"
        dest: "{{ firefox_config_dir }}/{{ firefox_profile_dir }}/user.js"
        mode: "0600"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    # https://mozilla.github.io/policy-templates/
    - name: Enable enterprise policies
      ansible.builtin.template:
        src: "policies.json.j2"
        dest: "{{ firefox_config_dir }}/{{ firefox_profile_dir }}/policies.json"
        mode: "0644"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Add required environment variables
      ansible.builtin.copy:
        dest: /etc/profile.d/firefox_env.sh
        content: |
          #!/bin/sh
          {% for var in firefox_env_vars %}
          export {{ var.name }}={{ var.value }}
          {% endfor %}
        mode: "0644"
        owner: root
        group: root
      become: true
