---
- name: Check installed firefox version
  block:
    - name: Get installed firefox version
      ansible.builtin.command:
        cmd: "firefox --version"
      ignore_errors: true
      changed_when: false
      failed_when: false
      register: firefox_installed_version_cmd

    - name: Extract only the version into a variable
      ansible.builtin.set_fact:
        firefox_installed_version: "{{ (firefox_installed_version_cmd.stdout | regex_search('.*?([\\d.]+)', '\\1'))[0] | default('') }}"

    - name: Debug installed firefox version
      ansible.builtin.debug:
        var: firefox_installed_version
