---
- name: Ensure we are using apt
  ansible.builtin.fail:
    msg: "This role only supports {{ ansible_os_family }} systems that use apt as a package manager."
  when: ansible_pkg_mgr != "apt"

- name: Install firefox dependencies via apt
  when: ansible_pkg_mgr == "apt"
  block:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      become: true

    - name: Get firefox version from package manager
      ansible.builtin.command:
        cmd: "apt show {{ firefox_distro_pkgs | first }}"
      changed_when: false
      failed_when: false
      ignore_errors: true
      register: firefox_pkg_mgr_version_cmd
      when: "firefox_distro_pkgs is defined and firefox_distro_pkgs | length > 0"

    - name: Extract only the version into a variable
      ansible.builtin.set_fact:
        firefox_pkg_mgr_version: "{{ (firefox_pkg_mgr_version_cmd.stdout | default('') | regex_search('Version:\\ ([\\d\\.]+)', '\\1', multiline=True) | default([''], true)) | first }}"

    - name: Debug firefox version from package manager
      ansible.builtin.debug:
        var: firefox_pkg_mgr_version
