---
- name: Install firefox from source
  block:
    - name: Import installed firefox version check
      ansible.builtin.include_tasks: noauto_check_installed_version.yml
      when: firefox_installed_version is not defined

    - name: Force install if the version numbers do not match
      ansible.builtin.set_fact:
        firefox_force_install: true
      when:
        - firefox_installed_version is defined
        - firefox_installed_version != firefox_version

    - name: Install firefox from source
      when: firefox_installed_version is not defined or firefox_force_install
      block:
        - name: Uninstall current firefox installation
          ansible.builtin.include_tasks: noauto_uninstall.yml

        - name: Identify checksum
          block:
            - name: Download checksum file
              ansible.builtin.get_url:
                url: "{{ firefox_download_checksum_url }}"
                dest: "{{ firefox_download_dir }}"
                mode: "0755"
                owner: root
                group: root
              become: true

            - name: Get checksum file content
              ansible.builtin.command:
                cmd: "cat {{ firefox_download_dir }}/SHA256SUMS"
              changed_when: false
              register: firefox_checksum_file_cmd

            # BUG: regex_search does not match the checksum
            - name: Parse checksum file for tarball
              ansible.builtin.set_fact:
                firefox_download_checksum: "{{ firefox_checksum_file_cmd.stdout | regex_search('([0-9a-f]+)  {{ firefox_arch }}\/{{ firefox_language }}\/firefox-{{ firefox_version }}\\.tar\\.xz', '\\1') }}"

            - name: Debug checksum
              ansible.builtin.debug:
                var: firefox_download_checksum

            - name: Remove checksum file
              ansible.builtin.file:
                path: "{{ firefox_download_dir }}/SHA256SUMS"
                state: absent
              become: true

        - name: Determine Firefox archive type based on version
          ansible.builtin.set_fact:
            firefox_archive_type: >-
              {{ 'tar.bz2' if firefox_version is version('135.0', '<') else 'tar.xz' }}

        - name: Download firefox package
          ansible.builtin.get_url:
            url: "{{ firefox_download_url }}"
            dest: "{{ firefox_download_dir }}"
            checksum: "{{ firefox_download_checksum }}"
            mode: "0755"
            owner: root
            group: root
          become: true

        - name: Ensure firefox installation folder exists
          ansible.builtin.file:
            path: "{{ firefox_install_path }}"
            state: directory
            mode: "0755"
            owner: root
            group: root
          become: true

        - name: Extract archive
          ansible.builtin.unarchive:
            src: "{{ firefox_download_dir }}/firefox-{{ firefox_version }}.{{ firefox_archive_type }}"
            dest: "{{ firefox_install_path }}"
            remote_src: true
            extra_opts: ["--strip-components=1"]
            creates: "{{ firefox_install_path }}/firefox"
          become: true

        - name: Create firefox symlink
          ansible.builtin.file:
            src: "{{ firefox_install_path }}/firefox"
            dest: "/usr/local/bin/firefox"
            state: link
            force: true
            mode: "0755"
            owner: root
            group: root
          become: true

        - name: Remove archive
          ansible.builtin.file:
            path: "{{ firefox_download_dir }}/firefox-{{ firefox_version }}.{{ firefox_archive_type }}"
            state: absent
          become: true

    - name: Create desktop icon
      block:
        - name: Ensure desktop icon directory exists
          ansible.builtin.file:
            path: "/usr/local/share/applications"
            state: directory
            mode: "0755"
            owner: root
            group: root
          become: true

        - name: Create desktop icon
          ansible.builtin.template:
            src: "firefox.desktop.j2"
            dest: "/usr/local/share/applications/firefox.desktop"
            mode: "0644"
            owner: root
            group: root
          become: true
