---
- name: Ensure we are using pacman
  ansible.builtin.fail:
    msg: "This role only supports {{ ansible_os_family }} systems that use pacman as a package manager."
  when: ansible_pkg_mgr != "pacman"

- name: Checks firefox version in package manager
  when: ansible_pkg_mgr == "pacman"
  block:
    - name: Update pacman cache
      community.general.pacman:
        update_cache: true
      become: true

    - name: Get firefox version from package manager
      ansible.builtin.command:
        cmd: "pacman -Si {{ firefox_distro_pkgs[0] }}"
      changed_when: false
      failed_when: false
      ignore_errors: true
      register: firefox_pkg_mgr_version_cmd

    - name: Debug output
      ansible.builtin.debug:
        var: firefox_pkg_mgr_version_cmd

    - name: Extract only the version into a variable
      ansible.builtin.set_fact:
        firefox_pkg_mgr_version: "{{ (firefox_pkg_mgr_version_cmd.stdout | regex_search('Version.*?([\\d\\.]+)', '\\1', multiline=True))[0] }}"

    - name: Debug firefox version from package manager
      ansible.builtin.debug:
        var: firefox_pkg_mgr_version
