---
- name: Converge
  hosts: all

  vars:
    ansible_user: root
    firefox_profile_user_prefs:
      - name: "browser.fullscreen.autohide"
        value: "false"
    firefox_extensions:
      - id: "uBlock0@raymondhill.net"
        mode: "force_installed"
        url: "https://addons.mozilla.org/firefox/downloads/latest/ublock-origin/latest.xpi"

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      become: true
      when: ansible_os_family == 'Debian'

  roles:
    - role: pluggero.firefox
